name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - name: TSLint checks
      uses: mooyoul/tslint-actions@v1.1.1
      with:
        # Github Token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Path of TSLint configuration
        config: ${{ github.workspace }}/tslint.json
        project: ${{ github.workspace }}/tsconfig.json
